### PR TITLE
Travis-ci run end2end test also with openshift

### PR DESCRIPTION
**Pull request by clamoriniere1A**

### CODE REVIEW

**Comment by sdminonne** [comment]
Thanks @clamoriniere1A, having a look

**Comment by clamoriniere1A** [comment]
@sdminonne you can see here the error  about "insecure registry" when trying to start `oc cluster up` in travisci: https://travis-ci.org/clamoriniere1A/workflow-controller/jobs/342369190

**Comment by clamoriniere1A** [comment]
@sdminonne let me know if you are happy with the current state of this PR.

**Comment by sdminonne** [comment]
thanks will merge on green

**Pull request merged**
